export const QUESTION_TAGS: string[] = [
	'aesthetics',
	'animism',
	'anthropology',
	'art',
	'Buddhism',
	'Christianity',
	'cosmology',
	'culture',
	'ecology/environment',
	'epistemology/knowledge',
	'ethics',
	'Hinduism',
	'history',
	'human nature',
	'Islam',
	'Judaism',
	'language',
	'law',
	'literature',
	'metaphysics',
	'mind, body, and self',
	'music',
	'philosophy of religion',
	'politics',
	'psychology',
	'science',
	'social philosophy',
	'sociology',
	'theology',
];
